use wcdinspection;

select * from superadmins;


ALTER TABLE superadmins 
  CHANGE createdat created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHANGE updatedat updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;


ALTER TABLE superadmins 
  ADD COLUMN is_active TINYINT(1) DEFAULT 1,
  CHANGE createdat created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHANGE updatedat updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
  
  
  USE wcdinspection;

ALTER TABLE superadmins 
  ADD COLUMN is_active TINYINT(1) DEFAULT 1,
  ADD COLUMN otp VARCHAR(10) DEFAULT NULL,
  ADD COLUMN otp_expires_at TIMESTAMP NULL DEFAULT NULL;
  
  
  USE wcdinspection;

ALTER TABLE stateadmins 
  ADD COLUMN createdby INT DEFAULT NULL,
  ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
  
  
  select * from stateadmins;
  
  
  ALTER TABLE stateadmins 
  ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
  
  
  USE wcdinspection;

ALTER TABLE districtadmins ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE inspectionofficers ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE organizations ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE surveyassignments ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE inspectionreports ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;


USE wcdinspection;

ALTER TABLE districtadmins 
  ADD COLUMN createdby INT DEFAULT NULL,
  ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

select * from districtadmins;



USE wcdinspection;

ALTER TABLE districtadmins 
  ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;


